/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dpbhastpixayzkcyxbgx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYmhhc3RwaXhheXprY3l4Ymd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjkyNzEsImV4cCI6MjA3MzYwNTI3MX0.nVuukvJnC-xyRM-hOB3r-tgZPKG8wQ_GgzPIBHR_gaw"